var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");
'use strict';var dt,ft,gt,ht,jt,lt,mt,ot,pt,st,tt,ut,vt,nt,wt,kt,xt,yt,zt,At,Bt,Ct,Et,Ft,Gt,it,Ht,It,qt;dt=function(a,b){if(null!=a&&null!=a.Wc)a=a.Wc(a,b);else{var c=dt[$CLJS.ua(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=dt._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $CLJS.Wa("Spec.with-gen*",a);}return a};ft=function(a){if($CLJS.Ld(a)){var b=$CLJS.u(et);a=$CLJS.J(b,a);if($CLJS.Ld(a))a:for(;;)if($CLJS.Ld(a))a=$CLJS.J(b,a);else{b=a;break a}else b=a;return b}return a};
gt=function(a){if($CLJS.Ld(a)){var b=ft(a);if($CLJS.q(b))return b;throw Error(["Unable to resolve spec: ",$CLJS.t.g(a)].join(""));}return a};ht=function(a){return null!=a&&$CLJS.x===a.od?a:null};jt=function(a){var b=it.g(a);return $CLJS.q(b)?a:b};lt=function(a,b){return $CLJS.Ld(a)?a:$CLJS.q(jt(a))?$CLJS.V.i(a,kt,b):null!=a&&(a.s&131072||$CLJS.x===a.Ic)?$CLJS.$c(a,$CLJS.V.i($CLJS.ad(a),kt,b)):null};
mt=function(a){return $CLJS.Ld(a)?a:$CLJS.q(jt(a))?kt.g(a):null!=a&&(a.s&131072||$CLJS.x===a.Ic)?kt.g($CLJS.ad(a)):null};ot=function(a){var b=function(){var c=(c=$CLJS.Ld(a))?ft(a):c;if($CLJS.q(c))return c;c=ht(a);if($CLJS.q(c))return c;c=jt(a);return $CLJS.q(c)?c:null}();return $CLJS.q(jt(b))?lt(nt(b,null),mt(b)):b};
pt=function(a){if($CLJS.ya(null==a?"":String(a)))return null;a=$CLJS.U.h($CLJS.qj,$CLJS.Dj(a,"$"));if(2<=$CLJS.D(a)&&$CLJS.pe(function(c){return!$CLJS.ya(null==c?"":String(c))},a)){var b=$CLJS.nj($CLJS.pj,$CLJS.hj)(a);a=$CLJS.H(b,0,null);b=$CLJS.H(b,1,null);return $CLJS.W.g([$CLJS.Aj(".",a),"/",$CLJS.t.g(b)].join(""))}return null};st=function(a,b){a=ft(a);return $CLJS.q(jt(a))?$CLJS.V.i(a,qt,b):dt(rt.g(a),b)};
tt=function(a,b,c,d,e,f){this.form=a;this.td=b;this.Xc=c;this.qd=d;this.xd=e;this.Zd=f;this.s=393216;this.I=0};ut=function(a,b,c,d,e){if($CLJS.q(ht(b)))return $CLJS.q(c)?st(b,c):b;if($CLJS.q(jt(b)))return nt(b,c);if($CLJS.Ld(b)){a=ot(b);if($CLJS.q(a))b=a;else{if($CLJS.Ld(b))throw Error(["Unable to resolve spec: ",$CLJS.t.g(b)].join(""));b=null}return $CLJS.q(c)?st(b,c):b}return new tt(a,b,c,d,e,$CLJS.Q)};vt=function(a,b,c){this.Zc=a;this.Xc=b;this.de=c;this.s=393216;this.I=0};
nt=function(a,b){return new vt(a,b,$CLJS.Q)};wt=new $CLJS.y("cljs.core","map","cljs.core/map",-338988913,null);kt=new $CLJS.N("cljs.spec.alpha","name","cljs.spec.alpha/name",205233570);xt=new $CLJS.y(null,"p1__14923#","p1__14923#",231231058,null);yt=new $CLJS.y(null,"p1__14924#","p1__14924#",1124195563,null);zt=new $CLJS.y("cljs.spec.alpha","conformer","cljs.spec.alpha/conformer",2140085535,null);At=new $CLJS.N("cljs.spec.alpha","k","cljs.spec.alpha/k",-1602615178);
Bt=new $CLJS.y("cljs.core","fn","cljs.core/fn",-1065745098,null);Ct=new $CLJS.N("cljs.spec.alpha","v","cljs.spec.alpha/v",552625740);$CLJS.Dt=new $CLJS.N(null,"in","in",-1531184865);Et=new $CLJS.y(null,"%","%",-950237169,null);Ft=new $CLJS.N("cljs.spec.alpha","kvs-\x3emap","cljs.spec.alpha/kvs-\x3emap",579713455);Gt=new $CLJS.y(null,"k","k",-505765866,null);it=new $CLJS.N("cljs.spec.alpha","op","cljs.spec.alpha/op",-1269055252);
Ht=new $CLJS.N("cljs.spec.alpha","unknown","cljs.spec.alpha/unknown",651034818);It=new $CLJS.y("cljs.core","zipmap","cljs.core/zipmap",-1902130674,null);qt=new $CLJS.N("cljs.spec.alpha","gfn","cljs.spec.alpha/gfn",-593120375);var et=$CLJS.se($CLJS.Q),Kt=function(){function a(d,e){var f=Jt[$CLJS.ua(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=Jt._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw $CLJS.Wa("Specize.specize*",d);}function b(d){var e=Jt[$CLJS.ua(null==d?null:d)];if(null!=e)return e.g?e.g(d):e.call(null,d);e=Jt._;if(null!=e)return e.g?e.g(d):e.call(null,d);throw $CLJS.Wa("Specize.specize*",d);}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,
d,e)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.h=a;return c}(),Jt=function Jt(a){switch(arguments.length){case 1:return Jt.g(arguments[0]);case 2:return Jt.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.t.g(arguments.length)].join(""));}};Jt.g=function(a){return null!=a&&null!=a.jc?a.jc(a):Kt(a)};Jt.h=function(a,b){return null!=a&&null!=a.kc?a.kc(a,b):Kt(a,b)};Jt.F=2;$CLJS.N.prototype.jc=function(){return Jt(gt(this))};$CLJS.N.prototype.kc=function(){return Jt(gt(this))};
$CLJS.y.prototype.jc=function(){return Jt(gt(this))};$CLJS.y.prototype.kc=function(){return Jt(gt(this))};$CLJS.lg.prototype.jc=function(){return ut(this,this,null,null,null)};$CLJS.lg.prototype.kc=function(a,b){return ut(b,this,null,null,null)};
Jt._=function(){function a(c){var d=(d=(d="function"===typeof c)?d:null!=c?$CLJS.x===c.fd?!0:c.Pd?!1:$CLJS.Ua($CLJS.Za,c):$CLJS.Ua($CLJS.Za,c))?pt(c.name):d;return $CLJS.q(d)?ut(d,c,null,null,null):ut(Ht,c,null,null,null)}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return ut(d,c,null,null,null)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return ut(d,c,null,null,null)};return b}();
var rt=function rt(a){switch(arguments.length){case 1:return rt.g(arguments[0]);case 2:return rt.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.t.g(arguments.length)].join(""));}};rt.g=function(a){var b=ht(a);return $CLJS.q(b)?b:Jt(a)};rt.h=function(a,b){var c=ht(a);return $CLJS.q(c)?c:Jt(a,b)};rt.F=2;$CLJS.k=tt.prototype;$CLJS.k.Z=function(a,b){return new tt(this.form,this.td,this.Xc,this.qd,this.xd,b)};$CLJS.k.X=function(){return this.Zd};$CLJS.k.jc=function(){return this};
$CLJS.k.kc=function(){return this};$CLJS.k.od=$CLJS.x;$CLJS.k.Wc=function(a,b){return ut(this.form,this.td,b,this.qd,this.xd)};$CLJS.k=vt.prototype;$CLJS.k.Z=function(a,b){return new vt(this.Zc,this.Xc,b)};$CLJS.k.X=function(){return this.de};$CLJS.k.jc=function(){return this};$CLJS.k.kc=function(){return this};$CLJS.k.od=$CLJS.x;$CLJS.k.Wc=function(a,b){return nt.h?nt.h(this.Zc,b):nt.call(null,this.Zc,b)};
var Lt=$CLJS.Hj(zt,$CLJS.Hj($CLJS.Jh,new $CLJS.S(null,1,5,$CLJS.T,[xt],null),$CLJS.Hj(It,$CLJS.Hj(wt,At,xt),$CLJS.Hj(wt,Ct,xt))),$CLJS.Hj($CLJS.Jh,new $CLJS.S(null,1,5,$CLJS.T,[yt],null),$CLJS.Hj(wt,$CLJS.Hj(Bt,new $CLJS.S(null,1,5,$CLJS.T,[new $CLJS.S(null,2,5,$CLJS.T,[Gt,$CLJS.di],null)],null),new $CLJS.n(null,2,[At,Gt,Ct,$CLJS.di],null)),yt))),Mt=ut($CLJS.Hj(zt,$CLJS.Hj(Bt,new $CLJS.S(null,1,5,$CLJS.T,[Et],null),$CLJS.Hj(It,$CLJS.Hj(wt,At,Et),$CLJS.Hj(wt,Ct,Et))),$CLJS.Hj(Bt,new $CLJS.S(null,1,
5,$CLJS.T,[Et],null),$CLJS.Hj(wt,$CLJS.Hj(Bt,new $CLJS.S(null,1,5,$CLJS.T,[new $CLJS.S(null,2,5,$CLJS.T,[Gt,$CLJS.di],null)],null),new $CLJS.n(null,2,[At,Gt,Ct,$CLJS.di],null)),Et))),function(a){return $CLJS.og($CLJS.U.h(At,a),$CLJS.U.h(Ct,a))},null,!0,function(a){return $CLJS.U.h(function(b){var c=$CLJS.H(b,0,null);b=$CLJS.H(b,1,null);return new $CLJS.n(null,2,[At,c,Ct,b],null)},a)});
if(null==Mt)$CLJS.Xg.i(et,$CLJS.Ij,Ft);else{var Nt;var Ot=ht(Mt);if($CLJS.q(Ot))Nt=Ot;else{var Pt=jt(Mt);Nt=$CLJS.q(Pt)?Pt:$CLJS.J($CLJS.u(et),Mt)}var Qt=$CLJS.q(Nt)?Mt:ut(Lt,Mt,null,null,null);$CLJS.Xg.A(et,$CLJS.V,Ft,lt(Qt,Ft))};