var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./cljs.reader.js");require("./clojure.string.js");
'use strict';var nr=function(){var a=mr.env;const b=[];let c=0;for(const d in a)b[c++]=a[d];return b},pr=function(a){return null==a?null:","===a?!0:or.test(a)},qr=function(a){return null==a?null:!/[^0-9]/.test(a)},rr=function(a,b){a=parseInt(a,b);return $CLJS.q(isNaN(a))?-1:a},sr=function(a){if(null!=a&&null!=a.Wb)a=a.Wb(a);else{var b=sr[$CLJS.ua(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=sr._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Wa("Reader.read-char",a);}return a},
tr=function(a){if(null!=a&&null!=a.yc)a=a.yc(a);else{var b=tr[$CLJS.ua(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=tr._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Wa("Reader.peek-char",a);}return a},ur=function(a,b){if(null!=a&&null!=a.pd)a.pd(a,b);else{var c=ur[$CLJS.ua(null==a?null:a)];if(null!=c)c.h?c.h(a,b):c.call(null,a,b);else if(c=ur._,null!=c)c.h?c.h(a,b):c.call(null,a,b);else throw $CLJS.Wa("IPushbackReader.unread",a);}},vr=function(a){if(null!=a&&null!=a.Td)a=
a.Td(a);else{var b=vr[$CLJS.ua(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=vr._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Wa("IndexingReader.get-line-number",a);}return a},wr=function(a){if(null!=a&&null!=a.Rd)a=a.Rd(a);else{var b=wr[$CLJS.ua(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=wr._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Wa("IndexingReader.get-column-number",a);}return a},xr=function(a){if(null!=a&&null!=a.Sd)a=a.Sd(a);else{var b=
xr[$CLJS.ua(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=xr._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Wa("IndexingReader.get-file-name",a);}return a},yr=function(a,b){this.ba=a;this.wd=b;this.pc=0},zr=function(a){a:{var b=Array(1);if($CLJS.Zi(null))for(var c=0,d=$CLJS.z(null);;)if(d&&1>c)b[c]=$CLJS.B(d),c+=1,d=$CLJS.C(d);else break a;else for(c=0;;)if(1>c)b[c]=null,c+=1;else break}this.ud=a;this.Ub=b;this.qb=this.Oc=1},Ar=function(a){return null!=a?$CLJS.x===a.ue?
!0:!1:!1},Br=function(a){for(var b=a.Wb(null);;)if(pr.g?pr.g(b):pr.call(null,b))b=a.Wb(null);else return b},Cr=function(a){return"@"===a||"`"===a||"~"===a},Dr=function(a){return Ar(a)?new $CLJS.S(null,2,5,$CLJS.T,[vr(a),(wr(a)|0)-1|0],null):null},Er=function(a){if(""===a||!0===/:$/.test(a)||!0===/^::/.test(a))return null;var b=a.indexOf("/"),c=0<b?a.substring(0,b):null;if(null!=c){b+=1;if(b===$CLJS.D(a))return null;a=a.substring(b);return qr($CLJS.Nc(a,0))||""===a||!1!==/:$/.test(c)||"/"!==a&&-1!==
a.indexOf("/")?null:new $CLJS.S(null,2,5,$CLJS.T,[c,a],null)}return"/"===a||-1===a.indexOf("/")?new $CLJS.S(null,2,5,$CLJS.T,[null,a],null):null},Fr=function(a,b){a=$CLJS.oj(a,b);return $CLJS.H(a,0,null)===b},Jr=function(a){if(Fr(Gr,a)){var b=$CLJS.Se($CLJS.oj(Gr,a));if(null!=(b.g?b.g(2):b.call(null,2)))a=0;else{a="-"===(b.g?b.g(1):b.call(null,1));b=null!=(b.g?b.g(3):b.call(null,3))?new $CLJS.S(null,2,5,$CLJS.T,[b.g?b.g(3):b.call(null,3),10],null):null!=(b.g?b.g(4):b.call(null,4))?new $CLJS.S(null,
2,5,$CLJS.T,[b.g?b.g(4):b.call(null,4),16],null):null!=(b.g?b.g(5):b.call(null,5))?new $CLJS.S(null,2,5,$CLJS.T,[b.g?b.g(5):b.call(null,5),8],null):null!=(b.g?b.g(7):b.call(null,7))?new $CLJS.S(null,2,5,$CLJS.T,[b.g?b.g(7):b.call(null,7),parseInt(b.g?b.g(6):b.call(null,6))],null):new $CLJS.S(null,2,5,$CLJS.T,[null,null],null);var c=b.g?b.g(0):b.call(null,0);null==c?a=null:(b=parseInt(c,b.g?b.g(1):b.call(null,1)),a=a?-1*b:b,a=$CLJS.q(isNaN(a))?null:a)}}else Fr(Hr,a)?(b=$CLJS.Se($CLJS.oj(Hr,a)),a=null!=
(b.g?b.g(4):b.call(null,4))?parseFloat(b.g?b.g(1):b.call(null,1)):parseFloat(a)):Fr(Ir,a)?(b=$CLJS.Se($CLJS.oj(Ir,a)),a=b.g?b.g(1):b.call(null,1),b=b.g?b.g(2):b.call(null,2),a=$CLJS.q($CLJS.oj(/^\+/,a))?a.substring(1):a,a=parseInt(a)/parseInt(b)):a=null;return a},Kr=function(a,b,c){b=new $CLJS.n(null,2,[$CLJS.mi,$CLJS.Aq,$CLJS.Bq,b],null);a=Ar(a)?$CLJS.V.j(b,$CLJS.ik,xr(a),$CLJS.G([$CLJS.Mj,vr(a),$CLJS.Oj,wr(a)])):b;var d=$CLJS.ik.g(a);b=$CLJS.Mj.g(a);var e=$CLJS.Oj.g(a);d=$CLJS.q(d)?[$CLJS.t.g(d),
" "].join(""):null;b=$CLJS.q(b)?["[line ",$CLJS.t.g(b),", col ",$CLJS.t.g(e),"]"].join(""):null;c=$CLJS.ge($CLJS.t,d,b,$CLJS.q($CLJS.q(d)?d:b)?" ":null,c);throw $CLJS.Sq(c,a,null);},Lr=function(a,b){return Kr(a,$CLJS.Cq,$CLJS.G([$CLJS.de($CLJS.t,b)]))},Mr=function(a,b){a:{var c=$CLJS.Hh instanceof $CLJS.N?$CLJS.Hh.fa:null;switch(c){case "regex":c='#"';break a;case "string":c='"';break a;default:throw Error(["No matching clause: ",$CLJS.t.g(c)].join(""));}}return Lr(a,$CLJS.G(["Unexpected EOF reading ",
$CLJS.ng($CLJS.Hh)," starting ",$CLJS.ee($CLJS.t,c,b),"."]))},Nr=function(a,b){return Kr(a,$CLJS.Dq,$CLJS.G([$CLJS.de($CLJS.t,b)]))},Or=function(a,b){return Nr(a,$CLJS.G(["Invalid digit ",b," in unicode character."]))},Pr=function(a,b,c){b=1+b;if($CLJS.D(a)!==b)throw Nr(null,$CLJS.G(["Invalid unicode literal: \\",a,"."]));for(var d=1,e=0;;){if(d===b)return String.fromCharCode(e);var f=rr($CLJS.Nc(a,d),c);if(-1===f)return c=$CLJS.Nc(a,d),Nr(null,$CLJS.G(["Invalid digit ",c," in unicode character \\",
a,"."]));e=f+e*c;d+=1}},Qr=function(a,b){return Kr(a,$CLJS.Eq,$CLJS.G([$CLJS.de($CLJS.t,b)]))},Rr=function(){return function(){function a(c,d){var e=null;if(1<arguments.length){e=0;for(var f=Array(arguments.length-1);e<f.length;)f[e]=arguments[e+1],++e;e=new $CLJS.sc(f,0,null)}return b.call(this,c,e)}function b(c){return Qr(c,$CLJS.G(["Unreadable form"]))}a.F=1;a.G=function(c){var d=$CLJS.B(c);c=$CLJS.wc(c);return b(d,c)};a.j=b;return a}()},Sr=function(a){return Qr(a,$CLJS.G(["Octal escape sequence must be in range [0, 377]."]))},
Tr=function(a,b){return Qr(a,$CLJS.G(["Unmatched delimiter ",b,"."]))},Ur=function(a,b,c){return Qr(a,$CLJS.G(["Invalid character: ",c," found while reading ",$CLJS.ng(b),"."]))},Vr=function(a,b,c){return Qr(a,$CLJS.G(["Invalid ",$CLJS.ng(b),": ",c,"."]))},Wr=function(a,b,c,d){Qr(a,$CLJS.G(["The map literal starting with ",$CLJS.rq.h(!1,$CLJS.B(d)),$CLJS.q(b)?[" on line ",$CLJS.t.g(b)," column ",$CLJS.t.g(c)].join(""):null," contains ",$CLJS.D(d)," form(s). Map literals must contain an even number of forms."]))},
Xr=function(a,b){return function e(d){return new $CLJS.Md(null,function(){for(;;){var f=$CLJS.z(d);if(f){if($CLJS.hd(f)){var g=$CLJS.Vb(f),h=$CLJS.D(g),l=$CLJS.Pd(h);return function(){for(var p=0;;)if(p<h){var r=$CLJS.Uc(g,p),w=l;if(r instanceof $CLJS.y||r instanceof $CLJS.N){var A=$CLJS.nj($CLJS.Kd,$CLJS.ng)(r),F=$CLJS.H(A,0,null);A=$CLJS.H(A,1,null);var I=r instanceof $CLJS.y?$CLJS.W:$CLJS.Fg;r=null==F?I.h?I.h(a,A):I.call(null,a,A):$CLJS.E.h("_",F)?I.g?I.g(A):I.call(null,A):r}w.add(r);p+=1}else return!0}()?
$CLJS.Sd(l.ga(),e($CLJS.Wb(f))):$CLJS.Sd(l.ga(),null)}var m=$CLJS.B(f);return $CLJS.Id(m instanceof $CLJS.y||m instanceof $CLJS.N?function(){var p=$CLJS.nj($CLJS.Kd,$CLJS.ng)(m),r=$CLJS.H(p,0,null);p=$CLJS.H(p,1,null);var w=m instanceof $CLJS.y?$CLJS.W:$CLJS.Fg;return null==r?w.h?w.h(a,p):w.call(null,a,p):$CLJS.E.h("_",r)?w.g?w.g(p):w.call(null,p):m}():m,e($CLJS.wc(f)))}return null}},null,null)}(b)},Yr=function(a,b){return new $CLJS.Md(null,function(){var c=$CLJS.z(b);return c?$CLJS.Id($CLJS.B(c),
Yr(a,$CLJS.we(a,c))):null},null,null)},Zr=function(a,b){b=function(c){return function f(e){return new $CLJS.Md(null,function(){for(var g=e;;)if(g=$CLJS.z(g)){if($CLJS.hd(g)){var h=$CLJS.Vb(g),l=$CLJS.D(h),m=$CLJS.Pd(l);a:for(var p=0;;)if(p<l){var r=$CLJS.Uc(h,p),w=$CLJS.H(r,0,null);1<$CLJS.H(r,1,null)&&m.add(w);p+=1}else{h=!0;break a}return h?$CLJS.Sd(m.ga(),f($CLJS.Wb(g))):$CLJS.Sd(m.ga(),null)}m=$CLJS.B(g);h=$CLJS.H(m,0,null);if(1<$CLJS.H(m,1,null))return $CLJS.Id(h,f($CLJS.wc(g)));g=$CLJS.wc(g)}else return null},
null,null)}($CLJS.Wq(c))}(b);return $CLJS.ge($CLJS.t,a,1<$CLJS.D(b)?"s":null,": ",$CLJS.Ae(", ",b))},$r=function(a,b,c){b=$CLJS.ng(b);Qr(a,$CLJS.G([Zr([String(b.charAt(0)).toUpperCase()+String(b.slice(1)).toLowerCase()," literal contains duplicate key"].join(""),c)]))},bs=function(a){var b="#"!==a;return b?(b="'"!==a)?(b=":"!==a)?as.g?as.g(a):as.call(null,a):b:b:b},cs=function(a,b,c,d){if($CLJS.Ta(c))return Lr(a,$CLJS.G(["Unexpected EOF while reading start of ",$CLJS.ng(b),"."]));if($CLJS.q($CLJS.q(d)?
Cr(c):d))return Ur(a,b,c);d=new $CLJS.Da;for(ur(a,c);;){if(pr(c)||bs(c)||null==c)return $CLJS.t.g(d);if(Cr(c))return Ur(a,b,c);d.append(sr(a));c=tr(a)}},fs=function(a,b,c){b=sr(a);if($CLJS.q(b)){var d=ds.g?ds.g(b):ds.call(null,b);if($CLJS.q(d))return d.i?d.i(a,b,c):d.call(null,a,b,c);ur(a,b);return es.i?es.i(a,b,c):es.call(null,a,b,c)}return Lr(a,$CLJS.G(["Unexpected EOF while reading dispatch character."]))},gs=function(a,b,c,d,e){for(var f=1,g=rr(b,c);;){if(-1===g)return Or(a,b);if(f!==d){var h=
tr(a);var l=pr(h);l||(l=as.g?as.g(h):as.call(null,h),l=$CLJS.q(l)?l:null==h);if($CLJS.q(l))return $CLJS.q(e)?Nr(a,$CLJS.G(["Invalid unicode literal. Unicode literals should be ",d,"characters long. ","Value supplied is ",f," characters long."])):String.fromCharCode(g);l=rr(h,c);sr(a);if(-1===l)return Or(a,h);g=l+g*c;f+=1}else return String.fromCharCode(g)}},hs=function(a){var b=sr(a);if(null!=b){b=bs(b)||Cr(b)||pr(b)?$CLJS.t.g(b):cs(a,$CLJS.Lq,b,!1);var c=b.length;if(1===c)return $CLJS.Nc(b,0);if("newline"===
b)return"\n";if("space"===b)return" ";if("tab"===b)return"\t";if("backspace"===b)return"\b";if("formfeed"===b)return"\f";if("return"===b)return"\r";if($CLJS.q($CLJS.Pq(b,"u")))return b=Pr(b,4,16),c=b.charCodeAt(),55295<c&&57344>c?(b=c.toString(16),a=Qr(a,$CLJS.G(["Invalid character literal \\u",b,"."]))):a=b,a;if($CLJS.q($CLJS.Pq(b,"o"))){--c;if(3<c)return Qr(a,$CLJS.G(["Invalid octal escape sequence in a character literal: ",b,". Octal escape sequences must be 3 or fewer digits."]));b=Pr(b,c,8);
return 255<(b|0)?Sr(a):b}return Qr(a,$CLJS.G(["Unsupported character: ",b,"."]))}return Lr(a,$CLJS.G(["Unexpected EOF while reading character."]))},ks=function(a,b,c,d){var e=Dr(c),f=$CLJS.H(e,0,null);e=$CLJS.H(e,1,null);b=null==b?null:$CLJS.$i(b);for(var g=$CLJS.Ob($CLJS.Re);;){var h=Br(c);if(!$CLJS.q(h)){var l=c,m=a,p=f,r=e,w=$CLJS.D(g);Lr(l,$CLJS.G(["Unexpected EOF while reading ",$CLJS.q(w)?["item ",$CLJS.t.g(w)," of "].join(""):null,$CLJS.ng(m),$CLJS.q(p)?[", starting at line ",$CLJS.t.g(p),
" and column ",$CLJS.t.g(r)].join(""):null,"."]))}if($CLJS.E.h(b,null==h?null:$CLJS.$i(h)))return $CLJS.Qb(g);l=as.g?as.g(h):as.call(null,h);$CLJS.q(l)?(h=l.i?l.i(c,h,d):l.call(null,c,h,d),g=h!==c?$CLJS.Pb(g,h):g):(ur(c,h),h=is?is(c,!0,null,d):js.call(null,c,!0,null,d),g=h!==c?$CLJS.Pb(g,h):g)}},ms=function(a,b,c){a=ks($CLJS.qh,")",a,c);return $CLJS.bd(a)?$CLJS.vc:$CLJS.de($CLJS.Hj,a)},ns=function(a,b,c){return ks($CLJS.yh,"]",a,c)},os=function(a,b,c){var d=Dr(a);b=$CLJS.H(d,0,null);d=$CLJS.H(d,1,
null);c=ks($CLJS.Qh,"}",a,c);var e=$CLJS.D(c),f=Yr(2,c),g=$CLJS.zj(f);!$CLJS.Uq(e)&&Wr(a,b,d,c);$CLJS.E.h($CLJS.D(g),$CLJS.D(f))||$r(a,$CLJS.Qh,f);if(e<=2*$CLJS.Bi)a=$CLJS.ej(c),a=new $CLJS.n(null,a.length/2,a,null);else a:for(a=$CLJS.ej(c),b=a.length,d=0,e=$CLJS.Ob($CLJS.xf);;)if(d<b)c=d+2,e=$CLJS.Rb(e,a[d],a[d+1]),d=c;else{a=$CLJS.Qb(e);break a}return a},ps=function(a,b){for(var c=function(){var g=new $CLJS.Da;g.append(b);return g}(),d=sr(a);;){if($CLJS.q(function(){var g=pr(d);if(g)return g;g=
as.g?as.g(d):as.call(null,d);return $CLJS.q(g)?g:null==d}())){var e=$CLJS.t.g(c);ur(a,d);var f=Jr(e);return $CLJS.q(f)?f:Qr(a,$CLJS.G(["Invalid number: ",e,"."]))}e=function(){var g=c;g.append(d);return g}();f=sr(a);c=e;d=f}},qs=function(a){var b=sr(a);switch(b){case "t":return"\t";case "r":return"\r";case "n":return"\n";case "\\":return"\\";case '"':return'"';case "b":return"\b";case "f":return"\f";case "u":return b=sr(a),-1===parseInt(b|0,16)?Qr(a,$CLJS.G(["Invalid unicode escape: \\u",b,"."])):
gs(a,b,16,4,!0);default:return qr(b)?(b=gs(a,b,8,3,!1),255<(b|0)?Sr(a):b):Qr(a,$CLJS.G(["Unsupported escape character: \\",b,"."]))}},rs=function(a){for(var b=new $CLJS.Da,c=sr(a);;){var d=c;if($CLJS.E.h(null,d))return Mr(a,$CLJS.G(['"',b]));if($CLJS.E.h("\\",d)){d=function(){var f=b;f.append(qs(a));return f}();var e=sr(a);b=d;c=e}else{if($CLJS.E.h('"',d))return $CLJS.t.g(b);d=function(){var f=b;f.append(c);return f}();e=sr(a);b=d;c=e}}},ss=function(a,b){b=cs(a,$CLJS.Yj,b,!0);if($CLJS.q(b))switch(b){case "nil":return null;
case "true":return!0;case "false":return!1;case "/":return $CLJS.Kq;default:var c=Er(b);c=$CLJS.q(c)?$CLJS.W.h(c.g?c.g(0):c.call(null,0),c.g?c.g(1):c.call(null,1)):null;return $CLJS.q(c)?c:Vr(a,$CLJS.Yj,b)}else return null},ts=function(a){var b=sr(a);if(pr(b))return Qr(a,$CLJS.G(["A single colon is not a valid keyword."]));b=cs(a,$CLJS.Jq,b,!0);var c=Er(b);if($CLJS.q($CLJS.q(c)?-1===b.indexOf("::"):c)){var d=c.g?c.g(0):c.call(null,0);c=c.g?c.g(1):c.call(null,1);return":"===$CLJS.Nc(b,0)?Vr(a,$CLJS.Jq,
[":",$CLJS.t.g(b)].join("")):$CLJS.Fg.h(d,c)}return Vr(a,$CLJS.Jq,[":",$CLJS.t.g(b)].join(""))},us=function(a,b,c){b=is?is(a,!0,null,c):js.call(null,a,!0,null,c);b=b instanceof $CLJS.N?$CLJS.uf([b,!0]):b instanceof $CLJS.y?new $CLJS.n(null,1,[$CLJS.uh,b],null):"string"===typeof b?new $CLJS.n(null,1,[$CLJS.uh,b],null):b;$CLJS.ed(b)||Qr(a,$CLJS.G(["Metadata cannot be ",$CLJS.rq.h(!1,b),". Metadata must be a Symbol, Keyword, String or Map."]));c=is?is(a,!0,null,c):js.call(null,a,!0,null,c);return null!=
c&&(c.s&131072||$CLJS.x===c.Ic)?$CLJS.$c(c,$CLJS.Jj.j($CLJS.G([$CLJS.ad(c),b]))):Qr(a,$CLJS.G(["Metadata can not be applied to ",$CLJS.rq.h(!1,c),". ","Metadata can only be applied to IMetas."]))},vs=function(a,b,c){b=ks($CLJS.Yh,"}",a,c);c=$CLJS.zj(b);$CLJS.E.h($CLJS.D(b),$CLJS.D(c))||$r(a,$CLJS.Yh,b);return c},ws=function(a){is?is(a,!0,null,!0):js.call(null,a,!0,null,!0);return a},xs=function(a,b,c){b=sr(a);b=cs(a,$CLJS.Mq,b,!0);var d=null==b?null:Er(b);if(null==d)var e=null;else e=$CLJS.H(d,0,
null),d=$CLJS.H(d,1,null),e=$CLJS.q(e)?null:d;return $CLJS.q(e)?"{"===Br(a)?(c=ks($CLJS.Mq,"}",a,c),!$CLJS.Uq($CLJS.D(c))&&Wr(a,null,null,c),b=Xr($CLJS.t.g(e),Yr(2,c)),c=Yr(2,$CLJS.wc(c)),$CLJS.E.h($CLJS.D($CLJS.zj(b)),$CLJS.D(b))||$r(a,$CLJS.Mq,b),$CLJS.og(b,c)):Qr(a,$CLJS.G(["Namespaced map with namespace ",b," does not specify a map."])):Qr(a,$CLJS.G(["Invalid value used as namespace in namespaced map: ",b,"."]))},ys=function(a,b,c){b=is?is(a,!0,null,c):js.call(null,a,!0,null,c);return $CLJS.E.h($CLJS.Gq,
b)?Number.NaN:$CLJS.E.h($CLJS.Iq,b)?Number.NEGATIVE_INFINITY:$CLJS.E.h($CLJS.Fq,b)?Number.POSITIVE_INFINITY:Qr(a,$CLJS.G([["Invalid token: ##",$CLJS.t.g(b)].join("")]))},as=function(a){switch(a){case '"':return rs;case ":":return ts;case ";":return zs;case "^":return us;case "(":return ms;case ")":return Tr;case "[":return ns;case "]":return Tr;case "{":return os;case "}":return Tr;case "\\":return hs;case "#":return fs;default:return null}},ds=function(a){switch(a){case "^":return us;case "{":return vs;
case "\x3c":return Rr();case "!":return zs;case "_":return ws;case ":":return xs;case "#":return ys;default:return null}},es=function(a,b,c){b=is?is(a,!0,null,c):js.call(null,a,!0,null,c);var d=is?is(a,!0,null,c):js.call(null,a,!0,null,c);b instanceof $CLJS.y||Qr(a,$CLJS.G(["Invalid reader tag: ",$CLJS.rq.h(!1,"Reader tag must be a symbol"),". Reader tags must be symbols."]));var e=$CLJS.J($CLJS.Oq.g(c),b);e=$CLJS.q(e)?e:$CLJS.Q.g?$CLJS.Q.g(b):$CLJS.Q.call(null,b);if($CLJS.q(e))return e.g?e.g(d):
e.call(null,d);c=$CLJS.bh.g(c);return $CLJS.q(c)?c.h?c.h(b,d):c.call(null,b,d):Qr(a,$CLJS.G(["No reader function for tag ",$CLJS.rq.h(!1,b),"."]))},js=function(a){switch(arguments.length){case 1:return As($CLJS.Q,arguments[0]);case 2:return As(arguments[0],arguments[1]);case 4:return is(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.t.g(arguments.length)].join(""));}},As=function(a,b){a=$CLJS.Xq(a);var c=$CLJS.J(a,$CLJS.Cq),d=!$CLJS.md(a,$CLJS.Cq);
return is(b,d,c,a)},is=function(a,b,c,d){try{for(;;){var e=sr(a);if(!pr(e)){if(null==e){if($CLJS.q(b)){b=a;var f=$CLJS.q(null)?Lr(b,$CLJS.G(["EOF while reading, starting at line ",null,"."])):Lr(b,$CLJS.G(["EOF while reading."]))}else f=c;return f}var g=a,h=e;if(qr(h)||("+"===h||"-"===h)&&qr(g.yc(null)))return ps(a,e);var l=as(e);if($CLJS.q(l)){var m=l.i?l.i(a,e,d):l.call(null,a,e,d);if(m!==a)return m}else return ss(a,e)}}}catch(p){if(p instanceof Error){f=p;if(f instanceof $CLJS.fh){b=$CLJS.Rq(f);
if($CLJS.E.h($CLJS.Aq,$CLJS.mi.g(b)))throw f;throw $CLJS.Sq(f.message,$CLJS.Jj.j($CLJS.G([new $CLJS.n(null,1,[$CLJS.mi,$CLJS.Aq],null),b,Ar(a)?new $CLJS.n(null,3,[$CLJS.Mj,vr(a),$CLJS.fk,wr(a),$CLJS.ik,xr(a)],null):null])),f);}throw $CLJS.Sq(f.message,$CLJS.Jj.j($CLJS.G([new $CLJS.n(null,1,[$CLJS.mi,$CLJS.Aq],null),Ar(a)?new $CLJS.n(null,3,[$CLJS.Mj,vr(a),$CLJS.fk,wr(a),$CLJS.ik,xr(a)],null):null])),f);}throw p;}},Bs=function(a){var b=new $CLJS.n(null,3,[$CLJS.Oq,$CLJS.u($CLJS.lr),$CLJS.bh,$CLJS.u($CLJS.kr),
$CLJS.Cq,null],null);return $CLJS.q($CLJS.q(a)?$CLJS.fr.h(a,""):a)?As(b,new zr(new yr(a,$CLJS.D(a)))):null},Cs=function(a){return $CLJS.Fg.g($CLJS.Zq($CLJS.Zq(a.toLowerCase(),"_","-"),".","-"))},Ds=function(a){var b=Cs($CLJS.ng(a));$CLJS.E.h(a,b)||$CLJS.Ji.j($CLJS.G(["Warning: environ key",a,"has been corrected to",b]));return b},Es=function(a,b){if("string"===typeof b)return b;$CLJS.Ji.j($CLJS.G(["Warning: environ value",$CLJS.Hi.j($CLJS.G([b])),"for key",a,"has been cast to string"]));return $CLJS.t.g(b)},
Fs=function(){return $CLJS.vf.h($CLJS.Q,$CLJS.U.h(function(a){var b=$CLJS.H(a,0,null);a=$CLJS.H(a,1,null);return new $CLJS.S(null,2,5,$CLJS.T,[Cs(b),a],null)},$CLJS.og($CLJS.za(mr.env),nr())))},Hs=function(){var a=$CLJS.q(Gs.ve(".lein-env"))?$CLJS.t.g(Gs.we(".lein-env")):null;return $CLJS.q(a)?$CLJS.vf.h($CLJS.Q,function(){return function d(c){return new $CLJS.Md(null,function(){for(;;){var e=$CLJS.z(c);if(e){if($CLJS.hd(e)){var f=$CLJS.Vb(e),g=$CLJS.D(f),h=$CLJS.Pd(g);a:for(var l=0;;)if(l<g){var m=
$CLJS.Uc(f,l),p=$CLJS.H(m,0,null),r=$CLJS.H(m,1,null);m=h;p=new $CLJS.S(null,2,5,$CLJS.T,[Ds(p),Es(p,r)],null);m.add(p);l+=1}else{f=!0;break a}return f?$CLJS.Sd(h.ga(),d($CLJS.Wb(e))):$CLJS.Sd(h.ga(),null)}f=$CLJS.B(e);h=$CLJS.H(f,0,null);f=$CLJS.H(f,1,null);return $CLJS.Id(new $CLJS.S(null,2,5,$CLJS.T,[Ds(h),Es(h,f)],null),d($CLJS.wc(e)))}return null}},null,null)}(Bs(a))}()):null},or=/[\s]/;yr.prototype.Wb=function(){if(this.wd>this.pc){var a=this.ba.charAt(this.pc);this.pc+=1;return a}return null};
yr.prototype.yc=function(){return this.wd>this.pc?this.ba.charAt(this.pc):null};zr.prototype.Wb=function(){var a=this.qb<this.Oc?this.Ub[this.qb]:this.ud.Wb(null);this.qb<this.Oc&&(this.qb+=1);return null==a?null:$CLJS.$i(a)};zr.prototype.yc=function(){var a=this.qb<this.Oc?this.Ub[this.qb]:this.ud.yc(null);return null==a?null:$CLJS.$i(a)};zr.prototype.pd=function(a,b){if($CLJS.q(b)){if(0===this.qb)throw Error("Pushback buffer is full");--this.qb;return this.Ub[this.qb]=b}return null};
var Gr=/^([-+]?)(?:(0)|([1-9][0-9]*)|0[xX]([0-9A-Fa-f]+)|0([0-7]+)|([1-9][0-9]?)[rR]([0-9A-Za-z]+)|0[0-9]+)(N)?$/,Ir=/([-+]?[0-9]+)\/([0-9]+)/,Hr=/([-+]?[0-9]+(\.[0-9]*)?([eE][-+]?[0-9]+)?)(M)?/,zs=function zs(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return zs.j(arguments[0],1<c.length?new $CLJS.sc(c.slice(1),0,null):null)};zs.j=function(a){for(;;){var b=a.Wb(null);if("\n"===b||"\n"===b||null==b)break}return a};zs.F=1;
zs.G=function(a){var b=$CLJS.B(a);a=$CLJS.C(a);return this.j(b,a)};var Is="undefined"!==typeof require,Gs=Is?require("fs"):null,mr=Is?require("process"):null;
if(Is){for(var Js=$CLJS.G([Hs(),Fs()]),Ks=$CLJS.z($CLJS.Vq($CLJS.Pe,$CLJS.de($CLJS.ui,Js))),Ls=null,Ms=0,Ns=0;;)if(Ns<Ms){var Os=Ls.K(null,Ns),Ps=$CLJS.H(Os,0,null),Qs=$CLJS.H(Os,1,null),Rs=$CLJS.U.h($CLJS.Qe,Qs);$CLJS.C(Qs)&&$CLJS.fr.h($CLJS.B(Rs),$CLJS.hj(Rs))&&$CLJS.Ji.j($CLJS.G(["Warning: environ value",$CLJS.B(Rs),"for key",Ps,"has been overwritten with",$CLJS.hj(Rs)]));Ns+=1}else{var Ss=$CLJS.z(Ks);if(Ss){var Ts=Ss;if($CLJS.hd(Ts)){var Us=$CLJS.Vb(Ts),Vs=$CLJS.Wb(Ts),Ws=Us,Xs=$CLJS.D(Us);Ks=
Vs;Ls=Ws;Ms=Xs}else{var Ys=$CLJS.B(Ts);Ps=$CLJS.H(Ys,0,null);Qs=$CLJS.H(Ys,1,null);Rs=$CLJS.U.h($CLJS.Qe,Qs);$CLJS.C(Qs)&&$CLJS.fr.h($CLJS.B(Rs),$CLJS.hj(Rs))&&$CLJS.Ji.j($CLJS.G(["Warning: environ value",$CLJS.B(Rs),"for key",Ps,"has been overwritten with",$CLJS.hj(Rs)]));Ks=$CLJS.C(Ts);Ls=null;Ms=0}Ns=0}else break}$CLJS.de($CLJS.Jj,Js)};